spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voce_aluga
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  thymeleaf:
    cache: false
